# Generated by Django 5.0.2 on 2025-04-22 15:55

import datetime
import django.core.validators
import savings.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savingsgoal',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='savingsgoal',
            name='max_daily_saving',
        ),
        migrations.RemoveField(
            model_name='savingsgoal',
            name='total_days',
        ),
        migrations.RemoveField(
            model_name='savingsgoal',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='savingsgoal',
            name='current_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='savingsgoal',
            name='daily_savings_plan',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='savingsgoal',
            name='start_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='savingsgoal',
            name='target_date',
            field=models.DateField(default=savings.models.get_default_target_date),
        ),
        migrations.AlterField(
            model_name='savingsgoal',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('JPY', 'Japanese Yen'), ('AUD', 'Australian Dollar'), ('CAD', 'Canadian Dollar'), ('CHF', 'Swiss Franc'), ('CNY', 'Chinese Yuan'), ('INR', 'Indian Rupee'), ('BRL', 'Brazilian Real'), ('RUB', 'Russian Ruble'), ('ZAR', 'South African Rand'), ('SGD', 'Singapore Dollar'), ('NZD', 'New Zealand Dollar'), ('SEK', 'Swedish Krona'), ('NOK', 'Norwegian Krone'), ('DKK', 'Danish Krone'), ('PLN', 'Polish Złoty'), ('MXN', 'Mexican Peso'), ('KRW', 'South Korean Won')], default='USD', max_length=3),
        ),
        migrations.AlterField(
            model_name='savingsgoal',
            name='goal_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
