# Generated by Django 5.0.2 on 2025-04-24 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0002_achievement_rename_current_streak_userprofile_streak_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savingsgoal',
            name='daily_savings_plan',
        ),
        migrations.CreateModel(
            name='DailySaving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('completed', models.BooleanField(default=False)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('savings_goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_savings', to='savings.savingsgoal')),
            ],
            options={
                'ordering': ['day_number'],
                'unique_together': {('savings_goal', 'day_number')},
            },
        ),
    ]
