# Generated by Django 5.0.2 on 2025-04-22 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0002_remove_savingsgoal_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savingsgoal',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('JPY', 'Japanese Yen'), ('AUD', 'Australian Dollar'), ('CAD', 'Canadian Dollar'), ('CHF', 'Swiss Franc'), ('CNY', 'Chinese Yuan'), ('INR', 'Indian Rupee'), ('PKR', 'Pakistani Rupee'), ('BRL', 'Brazilian Real'), ('RUB', 'Russian Ruble'), ('ZAR', 'South African Rand'), ('SGD', 'Singapore Dollar'), ('NZD', 'New Zealand Dollar'), ('SEK', 'Swedish Krona'), ('NOK', 'Norwegian Krone'), ('DKK', 'Danish Krone'), ('PLN', 'Polish Złoty'), ('MXN', 'Mexican Peso'), ('KRW', 'South Korean Won')], default='USD', max_length=3),
        ),
    ]
