# Generated by Django 5.0.2 on 2025-04-24 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0003_add_end_date'),
        ('savings', '0005_savingstemplate_and_more'),
    ]

    operations = [
    ]
