# Generated by Django 5.0.2 on 2025-04-24 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0008_userprofile_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motivationpost',
            name='goal',
        ),
    ]
