# Generated by Django 5.0.2 on 2025-04-25 07:22

import django.db.models.deletion
import savings.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0009_remove_motivationpost_goal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavingsTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('suggested_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('suggested_duration', models.IntegerField(help_text='Duration in days')),
                ('tips', models.TextField()),
                ('icon', models.CharField(default='fas fa-piggy-bank', max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='motivationpost',
            options={},
        ),
        migrations.RenameField(
            model_name='motivationpost',
            old_name='content',
            new_name='note',
        ),
        migrations.RenameField(
            model_name='savingsgoal',
            old_name='goal_amount',
            new_name='target_amount',
        ),
        migrations.RemoveField(
            model_name='savingsgoal',
            name='daily_savings_plan',
        ),
        migrations.RemoveField(
            model_name='savingsgoal',
            name='purpose',
        ),
        migrations.RemoveField(
            model_name='savingsgoal',
            name='target_date',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='avatar',
        ),
        migrations.AddField(
            model_name='dailysaving',
            name='actual_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='motivationpost',
            name='goal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='motivation_posts', to='savings.savingsgoal'),
        ),
        migrations.AddField(
            model_name='savingsgoal',
            name='allow_gifts',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='savingsgoal',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='savingsgoal',
            name='gift_link',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='savingsgoal',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='savingsgoal',
            name='motivation_image',
            field=models.ImageField(blank=True, null=True, upload_to='motivation_images/'),
        ),
        migrations.AddField(
            model_name='savingsgoal',
            name='motivation_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='savingsgoal',
            name='name',
            field=models.CharField(default='Unnamed Goal', max_length=100),
        ),
        migrations.AddField(
            model_name='savingsgoal',
            name='template',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='dark_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_pro',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='referral_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='savingsgoal',
            name='end_date',
            field=models.DateField(blank=True, default=savings.models.get_default_target_date, null=True),
        ),
        migrations.AlterField(
            model_name='savingsgoal',
            name='start_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='ChallengeParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('amount_saved', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('completed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GiftContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('anonymous', models.BooleanField(default=False)),
                ('contributor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gift_contributions', to='savings.savingsgoal')),
            ],
        ),
        migrations.CreateModel(
            name='SavingsChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('reward_points', models.IntegerField(default=100)),
                ('participants', models.ManyToManyField(through='savings.ChallengeParticipation', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='challengeparticipation',
            name='challenge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='savings.savingschallenge'),
        ),
        migrations.AlterUniqueTogether(
            name='challengeparticipation',
            unique_together={('user', 'challenge')},
        ),
    ]
