# Generated by Django 5.0.2 on 2025-04-25 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0006_userprofile_is_premium'),
        ('savings', '0010_savingstemplate_alter_motivationpost_options_and_more'),
    ]

    operations = [
    ]
